### ISSUE TITLE
schema.xml refers to non-existant class

### ISSUE THREAD

**Issue by averagehat** [DCGenomics/seqr#43]
see [here](https://github.com/NCBI-Hackathons/seqr/blob/26a09883e858a8fec2a225a558302ee4489c392c/testdata/solr/sequence/conf/schema.xml#L309)

**Comment by lianyi** [comment]
It should be in the [jar file](https://github.com/NCBI-Hackathons/seqr/blob/master/testdata/solr/lib/seqr-tokenizer-4.10.4-SNAPSHOT.jar). And the implementation should be in the tokenizer branch.  However, since we refactor the code to favor the command.line version, where the tokenizer won't fit in the same source code as it has to be a solr plugin, we might want to create another repository to host the tokenizer code. I'll follow up with this, but please reopen the issue this is a blocker to get the seqr.commandline version to work.

**Comment by averagehat** [comment]
Yes I realized this is what was happening. It's a bit sneaky because the jar file shares a file structure with that project. 

Do you think the tokenizer code is a good candidate for BioSolr? I can't quite pin down the scope of that project. If not, we are working on extending solr as well #44 VDBWRAIR/bio_pieces/#62, maybe we I can pull out some stuff that would fit into a cohesive plugin with the tokenizer stuff.

**Comment by lianyi** [comment]
Right, ideally we should spin off that code as the tokenizer code was loaded by solr, not seqr.cmd directly. I meet with Lewis last week on this topic, and it would be easier and less confusing to create another git repository( will check with Lewis,  and Sameer, the lead of BioSolr, if needed).

-lianyi
